package io.daobab.example.springboot.blank;

import io.daobab.Select;
import io.daobab.example.springboot.blank.dao.pizza.PizzaDataBase;
import io.daobab.example.springboot.blank.dao.pizza.PizzaTables;
import io.daobab.model.ProjectionBox;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

import static io.daobab.statement.condition.Operator.GT;
import static io.daobab.statement.condition.Operator.LIKE;
import static io.daobab.statement.where.base.Where.AND;

@RestController
@RequestMapping("/test")
public class Controller implements PizzaTables {

    //Inject here your DataBaseTarget generated by Daobab
    private @Autowired
    PizzaDataBase db;



    @GetMapping("/t01")
    public Long t01(){ return Select.many(db,tabPizza).countAny(); }

    @GetMapping("/t02")
    public List<String> t02(){ return Select.many(db,tabIngredient.colName()).where(tabIngredient.colName(),LIKE,"%A%").result(); }

    @GetMapping("/t03")
    public ProjectionBox t03(){ return Select.many(db,tabPizza.colID(),tabPizza.colName()).where(tabPizza.colID(),GT,toBigDecimal(10)).result(); }

    @GetMapping("/t04")
    public List<String> t04(){ return Select.many(db,tabPizza.colName()).orderAscBy(tabPizza.colName()).result(); }

    @GetMapping("/t05")
    public List<String> t05(){  return Select.many(db,tabIngredient.colName())
        .join(tabPizzaIngredient,tabIngredient.colIngredientId())
        .join(tabPizza,tabPizzaIngredient.colPizzaId(),AND().and(tabPizza.colName(),"CIAO ROMA"))
        .result(); }
}
